### ISSUE TITLE
The Riccione font does not support locale glyphs

### ISSUE THREAD

**Issue by bloodwiing** [anyproto/.github#3]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The "Narystė" (Membership) text in the settings uses the fallback font (Inter) for the letter 'ė'

![Anytype_2024-04-26_16-04-02](https://github.com/anyproto/.github/assets/13348029/1e2594d7-d928-49f3-923f-cdd03882a450)

### Expected Behavior

The "Narystė" (Membership) text in the settings should have a consistent font

### Steps To Reproduce

1. Switch to the Lithuanian interface language (lt.: Lietuvių)
2. Go to membership settings

### Environment

```markdown
- OS: Windows 11 Pro
- Version: 0.40.8
```

### Anything else?

I had a look into it and it simply turns out that the font Anytype uses has a pretty limited number of glyphs for internationalization

I checked all Lithuanian ones first: "ąčęėįšųūž". Plus a few additional punctuation marks.

And this is how the font renders it

![pulse-browser_2024-04-26_16-07-19](https://github.com/anyproto/.github/assets/13348029/b4cf138e-03de-468f-b1f9-e9c1c08c9174)

The font doesn't allow modifications due to the license, but, even then, this doesn't seem like a good solution 

Maybe a new font or more fallback ones?

**Comment by bloodwiing** [comment]
I have no idea how I got on the .github repository?

I'll move to the l10 one

**Comment by ThatOneCalculator** [comment]
Seems the issue template leads here sometimes, see #5 lol
